### ISSUE TITLE
need of help GPD winmax2 cannot be read correctly

### ISSUE THREAD

**Issue by danyi** [danyi/HandyPT#1]
![image](https://user-images.githubusercontent.com/1498746/201094089-5a99b026-22ca-4d73-b458-80a971f86ba7.png)
![image](https://user-images.githubusercontent.com/1498746/201093680-7ad1204e-5352-44ea-b8a2-9a4130e661b4.png)
![image](https://user-images.githubusercontent.com/1498746/201142639-46f2a28f-7f4f-49b9-b1fb-b3af042300d1.png)

GPD winmax2 cannot be read correctly
I changed the parameters so he could recognize it
But it doesn't work
I'm sorry to trouble you
@pastaq

**Comment by pastaq** [comment]
What is the output of `lscpu | grep "Model name" | cut -d : -f 2 | xargs`

line 386 and 391 need to be `} else if {` instead of `} if {`

also, 386 and 391 are identical except the case name, so you can combine them

```
} else if (id == "AOKZOE A1 AR07" || id == "ONEXPLAYER Mini Pro") {
            this.tdp_range.tdp_default_val = 16;
            this.tdp_range.tdp_max_boost = 8;
            this.tdp_range.tdp_max_val = 28;
            this.tdp_range.tdp_min_val = 4;
          } 
} else {
```

**Comment by danyi** [comment]
He's working fine. Thanks for your help
